version: 2
jobs:

  build:
    docker:
      - image: quay.io/quarkus/centos-quarkus-maven:20.1.0-java11
    resource_class: xlarge
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Native build
          command: mvn clean package -Pnative
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - src/main/docker
            - target

  containerize:
    docker:
      - image: docker:19.03.8
    working_directory: ~/workspace
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Docker build, tag & push
          command: |
            APP_VERSION=$(grep version target/maven-archiver/pom.properties | cut -d'=' -f2)
            docker build -f src/main/docker/Dockerfile -t myriadata/myria-invoice-api:$APP_VERSION .
            docker tag myriadata/myria-invoice-api:$APP_VERSION myriadata/myria-invoice-api:latest
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker push myriadata/myria-invoice-api:$APP_VERSION
            docker push myriadata/myria-invoice-api:latest

  deploy:
    docker:
      - image: circleci/node:14.5.0
    working_directory: ~/workspace
    steps:
      - add_ssh_keys:
          fingerprints:
            - "83:3d:06:66:02:95:95:18:d2:5a:11:45:24:7e:27:eb"
      - run:
          name: Deploy the latest image from dockerhub
          command: |
            git clone git+ssh://git@push-par-clevercloud-customers.services.clever-cloud.com/$CLEVER_APP_NAME.git
            npm install -g baconjs@3.0.10
            npm install -g clever-tools@2.6.1
            docker login
            cd $CLEVER_APP_NAME
            docker link $CLEVER_APP_NAME
            clever restart --without-cache

workflows:
  version: 2
  build-containerize:
    jobs:
      - build
      - containerize:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - containerize
          filters:
            branches:
              only: master