version: 2
jobs:

  build:
    docker:
      - image: quay.io/quarkus/centos-quarkus-maven:21.0.0-java11
    resource_class: xlarge
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Native build
          command: mvn clean package -Pnative
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - src/main/docker
            - target

  containerize:
    docker:
      - image: docker:20.10.2
    working_directory: ~/workspace
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Docker build, tag & push
          command: |
            APP_VERSION=$(grep version target/maven-archiver/pom.properties | cut -d'=' -f2)
            docker build -f src/main/docker/Dockerfile -t myriadata/myria-invoice-api:$APP_VERSION .
            docker tag myriadata/myria-invoice-api:$APP_VERSION myriadata/myria-invoice-api:latest
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker push myriadata/myria-invoice-api:$APP_VERSION
            docker push myriadata/myria-invoice-api:latest

  deploy:
    docker:
      - image: circleci/node:14.15.5
    working_directory: ~/workspace
    steps:
      - run:
          name: Deploy the latest image from dockerhub to production
          command: |
            npm install --prefix=$HOME/.local --global baconjs@0.7.83
            npm install --prefix=$HOME/.local --global superagent@5.1.0
            npm install --prefix=$HOME/.local --global clever-tools@2.8.0
            clever login --token $CLEVER_TOKEN --secret $CLEVER_SECRET
            clever link $CLEVER_APP_NAME
            clever restart --without-cache

workflows:
  version: 2
  myria-workflow:
    jobs:
      - build
      - containerize:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - containerize
          filters:
            branches:
              only: master